GET http://localhost:5148/times 

###

GET http://localhost:5148/times/4

###

POST http://localhost:5148/times/
Content-Type:  application/json 

{
    "nome": "Real Madrid",
    "cidade": "Madrid",
    "TitulosBrasileiros": 0,
    "TitulosMundiais": 10
}


